CREATE TABLE todo (
    id INTEGER PRIMARY KEY auto_increment,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(255) NOT NULL,
    is_done TINYINT DEFAULT 0 NOT NULL,
    update_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    create_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)